// mesh.ts — our own polygonal mesh, built in code ("Mesh Modeling" lecture).
//
// Data structure: FACE-VERTEX (slide 8)
//   - a vertex list:  the coordinates of every vertex
//   - a face list:    for every triangle, the indices of its 3 vertices
// This is the same structure an OBJ file uses (and our hw2 loader produced),
// but here the meshes are generated by functions instead of loaded from a file.

import * as THREE from "three";

/** A triangle mesh in face-vertex form (slide 8). */
export interface FVMesh {
  vertices: THREE.Vector3[];         // vertex list
  faces: [number, number, number][]; // face list: 3 vertex indices per triangle
}

export function emptyMesh(): FVMesh {
  return { vertices: [], faces: [] };
}

/** Adds one vertex and returns its index in the vertex list. */
function addVertex(m: FVMesh, p: THREE.Vector3): number {
  m.vertices.push(p);
  return m.vertices.length - 1;
}

/**
 * Adds triangle (i, j, k) so that it faces OUTWARD.
 * The face normal is the cross product of two edges (Basic Geometry, slide 8):
 *   N = (v_j − v_i) × (v_k − v_i)
 * The order of the vertices decides which way N points ("anti-commutativity", slide 8).
 * If N points away from `outward`, we swap two vertices to flip it.
 */
function addTriangle(m: FVMesh, i: number, j: number, k: number, outward: THREE.Vector3): void {
  const e1 = m.vertices[j].clone().sub(m.vertices[i]);
  const e2 = m.vertices[k].clone().sub(m.vertices[i]);
  const N = e1.cross(e2);
  if (N.dot(outward) < 0) m.faces.push([i, k, j]); // wrong way: swap j and k
  else m.faces.push([i, j, k]);
}

/**
 * Adds an axis-aligned box with centre (cx, cy, cz) and size (sx, sy, sz).
 * Each of the 6 sides gets its OWN 4 vertices ("normals per-vertex-per-face", slide 27):
 * a corner vertex is NOT shared between sides, so the box keeps its sharp edges
 * when vertex normals are computed later.
 */
export function addBox(m: FVMesh, cx: number, cy: number, cz: number, sx: number, sy: number, sz: number): void {
  const x0 = cx - sx / 2, x1 = cx + sx / 2;
  const y0 = cy - sy / 2, y1 = cy + sy / 2;
  const z0 = cz - sz / 2, z1 = cz + sz / 2;
  const V = (x: number, y: number, z: number) => new THREE.Vector3(x, y, z);
  // Each side: its outward direction and its 4 corners (in order around the side).
  const sides: [THREE.Vector3, THREE.Vector3[]][] = [
    [V(1, 0, 0),  [V(x1, y0, z0), V(x1, y1, z0), V(x1, y1, z1), V(x1, y0, z1)]], // +X
    [V(-1, 0, 0), [V(x0, y0, z0), V(x0, y1, z0), V(x0, y1, z1), V(x0, y0, z1)]], // −X
    [V(0, 1, 0),  [V(x0, y1, z0), V(x1, y1, z0), V(x1, y1, z1), V(x0, y1, z1)]], // +Y (top)
    [V(0, -1, 0), [V(x0, y0, z0), V(x1, y0, z0), V(x1, y0, z1), V(x0, y0, z1)]], // −Y (bottom)
    [V(0, 0, 1),  [V(x0, y0, z1), V(x1, y0, z1), V(x1, y1, z1), V(x0, y1, z1)]], // +Z
    [V(0, 0, -1), [V(x0, y0, z0), V(x1, y0, z0), V(x1, y1, z0), V(x0, y1, z0)]], // −Z
  ];
  for (const [outward, corners] of sides) {
    const [a, b, c, d] = corners.map((p) => addVertex(m, p));
    // A quad face is split into two triangles (triangular mesh, slide 2).
    addTriangle(m, a, b, c, outward);
    addTriangle(m, a, c, d, outward);
  }
}

/**
 * Adds a closed cylinder (e.g. a roller, a barbell, a flywheel).
 *   centre:   middle of the cylinder
 *   axis:     "x", "y" or "z" — the direction it runs along
 *   segments: how many flat sides approximate the round surface
 * Unlike the box, the rim vertices ARE shared by the round side and the flat cap
 * (a closed, "watertight" mesh, as most OBJ files are). Part 4 shows why this
 * matters when vertex normals are averaged (Mesh slide 11).
 */
export function addCylinder(
  m: FVMesh, centre: THREE.Vector3, axis: "x" | "y" | "z",
  radius: number, length: number, segments = 16
): void {
  // Build it along Y first, then rotate the coordinates onto the requested axis.
  const place = (x: number, y: number, z: number): THREE.Vector3 => {
    const p = axis === "y" ? new THREE.Vector3(x, y, z)
            : axis === "x" ? new THREE.Vector3(y, x, z)
            :                new THREE.Vector3(x, z, y);
    return p.add(centre);
  };
  const axisDir = place(0, 1, 0).sub(centre); // unit vector along the axis

  const bottom: number[] = [], top: number[] = [];
  for (let s = 0; s < segments; s++) {
    const t = (2 * Math.PI * s) / segments;
    bottom.push(addVertex(m, place(radius * Math.cos(t), -length / 2, radius * Math.sin(t))));
    top.push(addVertex(m, place(radius * Math.cos(t), +length / 2, radius * Math.sin(t))));
  }
  const cBottom = addVertex(m, place(0, -length / 2, 0)); // centre of each cap
  const cTop = addVertex(m, place(0, +length / 2, 0));

  for (let s = 0; s < segments; s++) {
    const n = (s + 1) % segments; // next segment (wraps around)
    // Round side: one quad (2 triangles) per segment, facing away from the axis.
    const mid = (2 * Math.PI * (s + 0.5)) / segments;
    const radial = place(Math.cos(mid), 0, Math.sin(mid)).sub(centre);
    addTriangle(m, bottom[s], bottom[n], top[n], radial);
    addTriangle(m, bottom[s], top[n], top[s], radial);
    // Caps: a fan of thin triangles around the cap centre.
    addTriangle(m, cBottom, bottom[n], bottom[s], axisDir.clone().negate());
    addTriangle(m, cTop, top[s], top[n], axisDir);
  }
}

/**
 * Vertex normals as the PLAIN AVERAGE of the incident face normals
 * (Mesh slide 11: "Vertex normal is average of incident face normals").
 * This is the same method used in hw3/hw5. Part 4 adds the area-weighted version.
 */
export function vertexNormalsAverage(m: FVMesh): THREE.Vector3[] {
  const normals = m.vertices.map(() => new THREE.Vector3());
  for (const [i, j, k] of m.faces) {
    const e1 = m.vertices[j].clone().sub(m.vertices[i]);
    const e2 = m.vertices[k].clone().sub(m.vertices[i]);
    const faceNormal = e1.cross(e2).normalize(); // unit length: every face counts the same
    normals[i].add(faceNormal);
    normals[j].add(faceNormal);
    normals[k].add(faceNormal);
  }
  return normals.map((n) => n.normalize());
}

/**
 * Vertex normals as the AREA-WEIGHTED average of the incident face normals
 * (Mesh slide 11: "What if some faces are larger than others?
 *  Vertex normal is weighted average of incident face normals. Weights are face areas").
 *
 * The trick: the length of the cross product of two edges is TWICE the triangle's area,
 *   |(v_j − v_i) × (v_k − v_i)| = 2 · Area
 * so adding the cross product WITHOUT normalizing it already weights each face by its area.
 * The only difference from vertexNormalsAverage() is the missing .normalize() on the face normal.
 */
export function vertexNormalsAreaWeighted(m: FVMesh): THREE.Vector3[] {
  const normals = m.vertices.map(() => new THREE.Vector3());
  for (const [i, j, k] of m.faces) {
    const e1 = m.vertices[j].clone().sub(m.vertices[i]);
    const e2 = m.vertices[k].clone().sub(m.vertices[i]);
    const weightedNormal = e1.cross(e2); // length = 2 · area → big faces count more
    normals[i].add(weightedNormal);
    normals[j].add(weightedNormal);
    normals[k].add(weightedNormal);
  }
  return normals.map((n) => n.normalize());
}

/** Short line segments from every vertex along its normal (debug view, like hw3 Part 4). */
export function normalLines(m: FVMesh, normals: THREE.Vector3[], length: number): THREE.BufferGeometry {
  const pts: THREE.Vector3[] = [];
  m.vertices.forEach((v, i) => pts.push(v, v.clone().addScaledVector(normals[i], length)));
  return new THREE.BufferGeometry().setFromPoints(pts);
}

/** Converts our face-vertex mesh into the arrays the GPU needs (positions, normals, indices). */
export function toBufferGeometry(m: FVMesh, normals: THREE.Vector3[]): THREE.BufferGeometry {
  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.Float32BufferAttribute(m.vertices.flatMap((v) => [v.x, v.y, v.z]), 3));
  g.setAttribute("normal", new THREE.Float32BufferAttribute(normals.flatMap((n) => [n.x, n.y, n.z]), 3));
  g.setIndex(m.faces.flat());
  return g;
}
